### ISSUE TITLE
install help

### ISSUE THREAD

**Issue by truesamurai** [sepehrdaddev/HashCobra#4]
How to install? When i follow your steps I get :
make: *** [Makefile:27: depend] error 2

**Comment by sepehrdaddev** [comment]
@sh1va73 Please check the Downloading section

**Comment by truesamurai** [comment]
I already check that but when I do that I get an error.
Did you not read my error I have?

**Comment by sepehrdaddev** [comment]
@sh1va73 I did, try cloning the repo like this: 
```git clone --recursive git@github.com:sepehrdaddev/hashcobra.git```

**Comment by truesamurai** [comment]
then I get this error:
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.                                                                                                                                                                                         
Please make sure you have the correct access rights                                                                     
and the repository exists.

**Comment by sepehrdaddev** [comment]
ok then maybe try this:
```
git clone --recursive https://github.com/sepehrdaddev/hashcobra.git
```

**Comment by sh1va73** [comment]
Still errors with make install: rocksdb/db.h does not exist

make -C third-party/libtomcrypt
make[1]: Map '/opt/hashcobra/third-party/libtomcrypt' wordt binnengegaan
make[1]: Er hoeft niets gedaan te worden voor 'library'.
make[1]: Map '/opt/hashcobra/third-party/libtomcrypt' wordt verlaten
g++ -O3 -Wall -Wextra -std=c++17 -march=native -s -Ithird-party/libtomcrypt/src/headers -c hashcobra.cpp  -o hashcobra.o
hashcobra.cpp:28:10: fatal error: rocksdb/db.h: Bestand of map bestaat niet
   28 | #include <rocksdb/db.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:19: hashcobra.o] Fout 1
